### ISSUE TITLE
[Sugestão de artigo]: Porque o "Engenheiro Full Stack" é tão problemático

### ISSUE THREAD

**Issue by titogarrido** [srebrasil/srebrasil.github.io#214]
### Nome

Tito Garrido

### Qual seu perfil no LinkedIn ou Twitter?

linkedin.com/in/titogarrido/

### Titulo original (em inglês ou portugês)

Why the Full Stack Engineer Is Problematic

### Autor(e)s

IT Revolution

### URL da publicação original

https://itrevolution.com/why-the-full-stack-engineer-is-problematic/

### Seus comentários

**_"Você pode ser bom em tudo?"_** É com essa pergunta que esse artigo lhe coloca para pensar sobre a carreira de "Full Stack". A quantidade de ferramentas, frameworks, linguagens de programação e métodos/modelos que aparecem e desaparecem todos os dias exigem um esforço enorme, e aprender um novo domínio de conhecimento exige tempo. Quando perguntado a uma equipe de engenheiros quanto tempo demora para uma nova contratação estar pronta para o trabalho, a média é de 6 a 12 meses.

Demora anos para você se torna especialista em qualquer coisa, e para DevOps isso não é diferente. Dominar uma habilidade significa que você ignorará intencionalmente outras habilidades para se concentrar na que deseja dominar. Nosso cérebro é vulnerável à sobrecarga, e essa sobrecarga ocorre à medida que estudamos assuntos cada vez mais complexos e realizamos tarefas cada vez mais complexas. E toda essa pressão pode causar o famoso _"Burnout"_.

Esperar que os indivíduos, incluindo nós mesmos, sejam qualificados “full stack” aumenta a carga cognitiva contínua para realizar o trabalho. Isso pode levar ao esgotamento e até, em alguns casos, a problemas de saúde mais sérios.

O autor então sugere **equipe full stack** ou invés de indivíduos full stack. Uma equipe full-stack tem as habilidades combinadas de seus membros para projetar, construir, implantar e operar software de forma eficaz em todos os ciclos de desenvolvimento de seus produtos. A mudança para equipes full-stack nos ajuda a oferecer a vantagem full-stack para nossas organizações sem os desafios de recrutar, desenvolver e manter desenvolvedores ou engenheiros full-stack.

Aqui estão algumas práticas recomendadas para ajudar a construir equipes full-stack:

- Especialistas em forma de T: todos são especialistas em uma ou algumas habilidades (a barra vertical do T), mas há uma compreensão básica e empatia por muitas ou todas as outras habilidades necessárias para construir e executar o produto (a barra horizontal)

- Todo mundo ensina: Ao ensinar, você entende melhor o assunto e cria empatia pelos outros.

- Mentalidade de crescimento: contrate membros que estejam abertos ao crescimento.

- Comunidades de prática: crie comunidades de práticas para que os membros de sua equipe possam desenvolver habilidades mais complexas e aprender as melhores práticas de outras pessoas.

- Sem Novos Silos: Não crie silos para demonstrar valor.

E você? Concorda com essa abordagem?

### Termo de conduta

- [X] Concordo com os termos de conduta

**Comment by rcsousa** [comment]
merged on pr #215
