### ISSUE TITLE
Abrace a Engenharia de Caos

### ISSUE THREAD

**Issue by dannemca-kyndryl** [srebrasil/srebrasil.github.io#328]
### Nome

Danne Aguiar

### Qual seu perfil no LinkedIn ou Twitter?

https://www.linkedin.com/in/dannemca/

### Titulo original (em inglês ou portugês)

Tabletop Exercises for Engineering Teams

### Autor(e)s

Paul Cichonski (https://medium.com/@paulcichonski)

### URL da publicação original

https://medium.com/@paulcichonski/tabletop-exercises-for-engineering-teams-a7a851b39c79

### Seus comentários

Engenharia do Caos consiste em propositadamente injetar erros no ambiente a fim de treinar o comportamento do time de SRE. Observando o tempo necessário para reconhecer o problema, identificar a falha, mitigar/resolver e indo mais além, como postmortems.
É um excelente exercício para SREs assumindo novas aplicações, colocando em prática os runbooks existentes e a arquitetura desenhada em cheque.
É bom estar preparado para o problema quando ele ocorrer "de verdade" durante a madrugada de domingo.
É bom para prever automações.
É bom para conhecer dependencias desconhecidas.
É bom para gastar seu error budget quando ele estiver sobrando...
Nesse artigo do Paul Cichonski, conheça um pouco mais sobre Tabletop Exercises, ou Wheel of Misfortune, pela Google.

### Termo de conduta

- [X] Concordo com os termos de conduta

**Comment by rcsousa** [comment]
> Engenharia do Caos consiste em propositadamente injetar erros no ambiente a fim de treinar o comportamento do time de SRE. Observando o tempo necessário para reconhecer o problema, identificar a falha, mitigar/resolver e indo mais além, como postmortems.
> 
> Quais os benefícios da engenharia de Caos:
> 
> * É um excelente exercício para SREs assumindo novas aplicações, colocando em prática os runbooks existentes e a arquitetura desenhada em cheque.
> * É bom estar preparado para o problema quando ele ocorrer "de verdade" durante a madrugada de domingo.
> * É bom para prever automações.
> * É bom para conhecer dependências desconhecidas.
> * É bom para gastar seu error budget quando ele estiver sobrando...
> 
> Nesse artigo do Paul Cichonski, conheça um pouco mais sobre Tabletop Exercises, ou Wheel of Misfortune, pela Google.
> 
> Leia o artigo na íntegra [aqui](https://medium.com/@paulcichonski/tabletop-exercises-for-engineering-teams-a7a851b39c79)

Revisado
