### ISSUE TITLE
[Sugestão de artigo]: Engenharia do Caos: Por onde começar?

### ISSUE THREAD

**Issue by mzerbinatti** [srebrasil/srebrasil.github.io#363]
### Nome

Michel Monteiro Zerbinati

### Qual seu perfil no LinkedIn ou Twitter?

https://www.linkedin.com/in/michelmonteirozerbinati/

### Titulo original (em inglês ou portugês)

Engenharia do Caos: Por onde começar?

### Autor(e)s

Michel Monteiro Zerbinati

### URL da publicação original

https://www.linkedin.com/pulse/engenharia-do-caos-por-onde-come%25C3%25A7ar-michel-monteiro-zerbinati/

### Seus comentários

Uma visão geral sobre Engenharia do Caos e algumas dicas iniciais com a intenção de incentivar a adoção da disciplina.

O artigo sugere um guia para iniciar a jornada. Os passos recomendados são:

1. Definir o steady state (sistema estável), ou seja, o estado normal da aplicação
2. Criar a hipótese de ataque
3. Desenvolver e executar o experimento que validará (ou não) a hipótese
4. Verificar/analisar o resultado do experimento

Os passos acima são, inclusive, os sugeridos pelo manifesto do Principles of Chaos Engineering.

Confiram o artigo na íntegra [aqui](https://www.linkedin.com/pulse/engenharia-do-caos-por-onde-come%25C3%25A7ar-michel-monteiro-zerbinati/)

### Termo de conduta

- [X] Concordo com os termos de conduta

**Comment by rcsousa** [comment]
Oi @mzerbinatti , consegue colocar um pouco mais de descrição sobre o que é artigo é? Bem breve mas que desperte o interesse das pessoas em se aprofundar com o seu artigo.

Abcs
